CREATE TABLE OMNI_USERS (
    ID NUMBER(19,0) primary key,
	LOGIN VARCHAR(150 CHARACTERS),
	PASSWORD VARCHAR(150 CHARACTERS),
	STATUS NUMBER(1) DEFAULT 0
);

CREATE TABLE USR (
    USR_KEY NUMBER(19,0) primary key,
    USR_EMP_NO VARCHAR(100 CHARACTERS),
	USR_UDF_MAINBRANCH VARCHAR(250 CHARACTERS),
	USR_UDF_TEMPBRANCH VARCHAR(250 CHARACTERS),
	USR_UDF_REBRANCHINGSTARTDATE DATE,
	USR_UDF_REBRANCHINGENDDATE DATE
);





