CREATE TABLE OMNI_USERS (
    ID NUMBER(19,0) primary key,
	LOGIN VARCHAR(150 CHARACTERS),
	PASSWORD VARCHAR(150 CHARACTERS),
	STATUS NUMBER(1) DEFAULT 0
);

CREATE TABLE OMNI_REQUEST (
    ID BIGINT auto_increment,
    OBJECT_ID VARCHAR(100 CHARACTERS) UNIQUE,
    EMP_NO VARCHAR(100 CHARACTERS),
	MAINBRANCH VARCHAR(250 CHARACTERS),
	TEMPBRANCH VARCHAR(250 CHARACTERS),
	REBRANCHINGSTARTDATE DATE,
	REBRANCHINGENDDATE DATE,
	CHANGED_AT TIMESTAMP,
	IS_SAVED NUMBER(1) DEFAULT 0,
	IS_PROCESSED NUMBER(1) DEFAULT 0,
	IS_PICKUP_SENT NUMBER(1) DEFAULT 0,
	IS_CLOSURE_SENT NUMBER(1) DEFAULT 0
);

CREATE TABLE OMNI_BLOCK_REQUEST (
    ID BIGINT auto_increment,
    OBJECT_ID VARCHAR(100 CHARACTERS) UNIQUE,
	ACTION VARCHAR(100 CHARACTERS),
	ACTION_DATE TIMESTAMP,
	CHANGED_AT TIMESTAMP,
	IS_PROCESSED NUMBER(1) DEFAULT 0,
	IS_PICKUP_SENT NUMBER(1) DEFAULT 0,
	IS_CLOSURE_SENT NUMBER(1) DEFAULT 0,
	IS_IN_PROCESS NUMBER(1) DEFAULT 0
);

CREATE TABLE OMNI_BLOCK_DATA (
    ID BIGINT auto_increment,
    OMNI_BLOCK_REQUEST_ID INTEGER,
    EMP_NUMBER VARCHAR,
    SOURCE_ID VARCHAR
);

CREATE TABLE OMNI_BLOCK_ATTACHMENT (
    ID BIGINT auto_increment,
    OMNI_BLOCK_REQUEST_ID INTEGER,
    OID VARCHAR(100 CHARACTERS),
	FILENAME VARCHAR(100 CHARACTERS),
    FILESIZE VARCHAR(100 CHARACTERS),
    ATTACHMENT VARCHAR
);

CREATE TABLE USR (
    USR_KEY NUMBER(19,0) primary key,
    USR_EMP_NO VARCHAR(100 CHARACTERS),
    USR_UDF_OBJECTID VARCHAR(100 CHARACTERS),
    USR_DISPLAY_NAME VARCHAR,
    USR_LOCKED NUMBER(1) DEFAULT 0,
    USR_UDF_EXTENSIONATTRIBUTE15 VARCHAR,
    USR_START_DATE DATE,
    USR_END_DATE DATE,
    USR_UDF_STARTDATEVACATION DATE,
    USR_UDF_ENDDATEVACATION DATE,
	USR_UDF_MAINBRANCH VARCHAR(250 CHARACTERS),
	USR_UDF_TEMPBRANCH VARCHAR(250 CHARACTERS),
	USR_UDF_REBRANCHINGSTARTDATE DATE,
	USR_UDF_REBRANCHINGENDDATE DATE
);

CREATE TABLE ORC (
    ORC_KEY BIGINT auto_increment,
    USR_KEY INTEGER
);

CREATE TABLE UD_ADUSER (
    ID BIGINT auto_increment,
    ORC_KEY INTEGER,
    UD_ADUSER_UID VARCHAR
);

CREATE TABLE OIU (
    ID BIGINT auto_increment,
    ORC_KEY INTEGER,
    OST_KEY INTEGER
);

CREATE TABLE OST (
    OST_KEY BIGINT auto_increment,
    OST_STATUS VARCHAR
);

CREATE TABLE LKV (
    LKV_KEY BIGINT auto_increment,
    LKU_KEY VARCHAR,
    LKV_DECODED VARCHAR
);

CREATE TABLE LKU (
    LKU_KEY BIGINT auto_increment,
    LKU_TYPE_STRING_KEY VARCHAR
);





